version: '3.3'

services:
  timbrella-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
    command: npm run dev
    depends_on:
      - pgadmin

  timbrella-api-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
    command: npm run build
    depends_on:
      - pgadmin

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: timbrella@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
